### ISSUE TITLE
what is compute_overlap

### ISSUE THREAD

**Issue by lucasjinreal** [Cli98/anchor_computation_tool#1]
there were no such package?

**Comment by Cli98** [comment]
> there were no such package?

@jinfagang Actually I have included them. It's a cython file.

Do you know how to load cython file?

**Comment by lucasjinreal** [comment]
Yes I know, where is this file?
![image](https://user-images.githubusercontent.com/21303438/81522514-67ce7480-937d-11ea-9c43-2fd14405a46d.png)

**Comment by lucasjinreal** [comment]
Did u forgot upload it ?

**Comment by Cli98** [comment]
> Did u forgot upload it ?

@jinfagang lol yes. Please check it now. Thank you for pointing out this for me.

**Comment by lucasjinreal** [comment]
Now? Still not seen it

**Comment by lucasjinreal** [comment]
Got it

**Comment by Cli98** [comment]
Great. I will post my test result for faster-Rcnn-Fpn tomorrow.

**Comment by Cli98** [comment]
Just close this... Feel free to reopen if you need
