### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Dicko87** [Cli98/anchor_computation_tool#10]
Hi there, please could you provide a link to the dataset in the notebook example so I may inspect the xml files as I have some errors I would like to debug. Thank you.

**Comment by Cli98** [comment]
@Dicko87 Coco dataset should work in this example. You can also describe the issue and I may be able to help debug.

**Comment by Dicko87** [comment]
Thanks for the reply, it’s just that the notebook reads xml files but I have json files from the coco dataset. I am trying to convert them to xml format to work with the notebook but want to check the structure is ok.

**Comment by Cli98** [comment]
This is not a bug as far as I can tell but a new feature to add instead. 

There are many repos can transform coco to voc. For example, https://github.com/JingyuanHu/COCO2VOC.

Just search google with keyword "transform coco to voc"

**Comment by Cli98** [comment]
Closed due to inactivity. Feel free to reopen for any further discussion.
