### ISSUE TITLE
Input ratios for anchor inspector may have format (h,w)?

### ISSUE THREAD

**Issue by SubramanianKrish** [Cli98/anchor_computation_tool#11]
I came across this repo while browsing issues in zylo117's EffDet. Great tool btw. Thanks for hosting.

Zylo's effdet implementation uses format (w,h) for his anchor box implementation. When I pass a set of ratios that have boxes which are wider and shorter (That's how the gt boxes are too), according to zylo's format, they'd be something like:
anchors_ratios: '[(0.9, 1.1), (1.2, 0.8), (2.2, 0.5)]'

When I pass it to the anchor inspector along with the training data directory, I see that I see a log of red boxes. Some green.
However, If i pass the inverted ratios, lots of green start popping up:
eg: [(1.1,0.9), (0.8,1.2), (0.5,2.2)]

So, is it possible that the format required for the anchor inspector is (h,w)?

**Comment by Cli98** [comment]
@SubramanianKrish Good point!

In my current implementation, The ratio for inspector should be (h,w). As I follow the numpy setup. If you are Opencv user, you may not happy about this.

I will double check the issue you raised and confirm you. If I am not remember wrong, then you are correct. May not reply you in time as I'm fixing my car next week.

**Comment by Cli98** [comment]
Closed due to inactivity. Feel free to reopen if needed

**Comment by SubramanianKrish** [comment]
@Cli98 Do put up a note of the same in the readme if possible. Thanks!

**Comment by Cli98** [comment]
Yup. I will do this man.
