### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by kimalaacer** [Cli98/anchor_computation_tool#12]
I was wondering if you can give me a template yaml files, and template xml annotation file. 
the below folder structure is within anchor_computation_tool. 

+---projects
|       mask.yml
+---datasets
|   +---mask
|   |   |   instances_train.json
|   |   |   instances_val.json              
|   +---train     
|   |   \---images
|   |           train1.png
|   |           train10.png
    +---val
|   |    \---images
|               val5.png
|               val6.png

the instances_train.json are COCO annotation that have bounding box and annotation. 
The mask.yaml has the project according to ZYLO117 recommendation. 

I need help on how to format the xml annotation file from the json file. 
Thanks,

**Comment by Cli98** [comment]
@kimalaacer Thank you for you interest. By now I'm busy with job hunting. So I may not be able to push code for your exact requirement.

For your questions,

1. I do not know why you need xml template. As ZYLO117's repo use nearly the same annotation file with mine.
2. Can you try with ZYLO117's default yaml template? Just change to your own parameter is enough. Let me know if this does not work. I will upload a new template then.

Thank you
