### ISSUE TITLE
anchor scale and anchor ratios in Yet-Another-EfficientDet-Pytorch

### ISSUE THREAD

**Issue by whut2962575697** [Cli98/anchor_computation_tool#2]
Thank you for your great work! But  I want to konw how to get customer anchor in Yet-Another-EfficientDet-Pytorch.

**Comment by Cli98** [comment]
> Thank you for your great work! But I want to konw how to get customer anchor in Yet-Another-EfficientDet-Pytorch.

Hi @whut2962575697 , you can try the notebook named "k_mean_anchor_size" and run code inside of it. If you only need bboxs, take the result from kmean. Else if you need anchor ratio/scale, take the output from anchor parameters

<img width="838" alt="image" src="https://user-images.githubusercontent.com/19630616/81561049-8eca7d80-9360-11ea-8b14-ec4c134de59e.png">

Kmean result -> check "out"
anchor ratio/scale -> check compute paras

As a side word, be aware of whether your detection program is height based or width based. You may need to flip the box of anchor parameter to correctly load your bboxs.

**Comment by dfayzur** [comment]
Hi,
Thanks for your excellent work. Can you please share an example with the following notebook to get anchor ratio/scale?

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/tutorial/train_shape.ipynb

**Comment by Cli98** [comment]
> Hi,
> Thanks for your excellent work. Can you please share an example with the following notebook to get anchor ratio/scale?
> 
> https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/tutorial/train_shape.ipynb

Hi @dfayzur , yes this is a good point. I will add it to my to-do list and test with that dataset. I will update once I finish.

**Comment by dfayzur** [comment]
@Cli98 : Thanks for considering it to your to-do list. Thanks in advance for your time on working on the dataset.

**Comment by Cli98** [comment]
> @Cli98 : Thanks for considering it to your to-do list. Thanks in advance for your time on working on the dataset.

I will close this issue for now... For the example you requested, I will post them ASAP.
