### ISSUE TITLE
nothing shows with inspect tool

### ISSUE THREAD

**Issue by lucasjinreal** [Cli98/anchor_computation_tool#3]
I enabled --anchors and --annotations,

but no annotations shows and no anchors shows (using defrault params)

![image](https://user-images.githubusercontent.com/21303438/81547231-27d3b580-93ae-11ea-92b9-6b2c6bccbd0c.png)

**Comment by Cli98** [comment]
@jinfagang Your are using repo from "Yet-Another-EfficientDet-Pytorch" right?

I'm not sure how you pass your parameter. Do not directly pass those two parameters from terminal, but instead pass them from yaml file. To do so, please open your configuration file under "projects" folder, then add following lines,

#Setup options for anchor visualization
no_gui: True
anchors: False
annotations: True

Just try it to see if you can work. 

For above image, by default both of them set to None, and that's why you see nothing.
I will add a yaml example to this repo shortly.

**Comment by lucasjinreal** [comment]
then why it can found image correctly?

**Comment by Cli98** [comment]
> then why it can found image correctly?

@jinfagang I'm not quite understand what you are asking. Can you clarify?

**Comment by lucasjinreal** [comment]
it can load image and show, but can not load annotations so that there were no box

**Comment by Cli98** [comment]
> it can load image and show, but can not load annotations so that there were no box

@jinfagang Did you follow what I mentioned above? If yes, can you copy and paste your yaml file here? It is okay if you use yaml file from "Yet-Another-EfficientDet-Pytorch"

**Comment by lucasjinreal** [comment]
I just clone this repo under Yet-Another-EfficientDet-Pytorch, in the root dir, then call it via:

```
python3 anchor_computation_tool/anchor_inspector.py -project_name projects/tl_4gpus_3x -dataset_path ./datasets/coco_tl --annotations --anchors
```

the ymal content are:

```
project_name: coco_tl  # also the folder name of the dataset that under data_path folder
train_set: train2017
val_set: val2017
num_gpus: 3

# mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# this is coco anchors, change it if necessary
# anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
# anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
# anchors_scales: '[0.02, 0.6, 2 ** (1.0 / 3.0)]'
# anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
# 0.25 still big, try 0.15
# anchors_scales: '[0.25, 0.5, 2 ** (2.0 / 3.0)]'
# anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

anchors_scales: '[0.1, 0.25, 2 ** (1.0 / 3.0)]'
anchors_ratios: '[(0.7, 0.7), (1.4, 0.7), (0.7, 1.4)]'

# must match your dataset's category_id.
# category_id is one_indexed,
# for example, index of 'car' here is 2, while category_id of is 3
obj_list: ['a', 'b', 'c', 'd',]
```

**Comment by lucasjinreal** [comment]
I saw you read anchors and annotations from yml file which I can not found it with default template:

```
    draw_para = {'anchors':params.anchors, 'annotations':params.annotations, 'no_gui':params.no_gui}
    print(draw_para)
```

what does this meaning? Does it should be command line flags?

**Comment by Cli98** [comment]
> I saw you read anchors and annotations from yml file which I can not found it with default template:
> 
> ```
>     draw_para = {'anchors':params.anchors, 'annotations':params.annotations, 'no_gui':params.no_gui}
>     print(draw_para)
> ```
> 
> what does this meaning? Does it should be command line flags?

Please check carefully for my previous reply. You did not follow what I suggested.

**Comment by Cli98** [comment]
> > I saw you read anchors and annotations from yml file which I can not found it with default template:
> > ```
> >     draw_para = {'anchors':params.anchors, 'annotations':params.annotations, 'no_gui':params.no_gui}
> >     print(draw_para)
> > ```
> > 
> > 
> > what does this meaning? Does it should be command line flags?
> 
> Please check carefully for my previous reply. You did not follow what I suggested.

@jinfagang Copy and paste your yml file and try it again

project_name: coco_tl  # also the folder name of the dataset that under data_path folder
train_set: train2017
val_set: val2017
num_gpus: 3

#mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

#this is coco anchors, change it if necessary
#anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
#anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
#anchors_scales: '[0.02, 0.6, 2 ** (1.0 / 3.0)]'
#anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
#0.25 still big, try 0.15
#anchors_scales: '[0.25, 0.5, 2 ** (2.0 / 3.0)]'
#anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

anchors_scales: '[0.1, 0.25, 2 ** (1.0 / 3.0)]'
anchors_ratios: '[(0.7, 0.7), (1.4, 0.7), (0.7, 1.4)]'

#must match your dataset's category_id.
#category_id is one_indexed,
#for example, index of 'car' here is 2, while category_id of is 3
obj_list: ['a', 'b', 'c', 'd',]
#Visualization options
no_gui: True
anchors: False
annotations: True

The reason that you see no bbox is, when you run from terminal directly, you need to pass some boolean parameters (i.e. anchors & annotations). However, there are some conversion required to translate input to boolean parameters and this needs lots of code. 

I do not think it is necessary for that and thus, just like what I said previously, try to pass them from yaml file instead. I have observed the issue you have during my testing phase and I believe this is a suitable solution. Yet if you still prefer a terminal option, just let me know.

**Comment by lucasjinreal** [comment]
@Cli98  Thanks for your dedicated reply. I followed your instructions an I can show anchors on image now.

But I am using kmeans to calculated anchor and I got output like this:

```
Accuracy: 86.76%
Boxes:
 [[ 68 150]
 [ 74 173]
 [156  68]]
computed paras:  ([2.125, 2.3125, 4.875], [(1, 2.2058823529411766), (1, 2.3378378378378377), (1, 0.4358974358974359)])
```

I suppose params is scales and ratios I need, so I copy paste to yml and visualize again, I found that this time no anchor shows at all.

Do u know what happen? How to check generated anchor is suitable or not?

**Comment by Cli98** [comment]
> @Cli98 Thanks for your dedicated reply. I followed your instructions an I can show anchors on image now.
> 
> But I am using kmeans to calculated anchor and I got output like this:
> 
> ```
> Accuracy: 86.76%
> Boxes:
>  [[ 68 150]
>  [ 74 173]
>  [156  68]]
> computed paras:  ([2.125, 2.3125, 4.875], [(1, 2.2058823529411766), (1, 2.3378378378378377), (1, 0.4358974358974359)])
> ```
> 
> I suppose params is scales and ratios I need, so I copy paste to yml and visualize again, I found that this time no anchor shows at all.
> 
> Do u know what happen? How to check generated anchor is suitable or not?

@jinfagang That's weird. I want to follow up with some questions,

1. which option you specific in kmean code? To clarify, I offer three options('s'(small),'m'(medium),'l'(large)) for three different categories. By default this is "l", means large. And I guess you choose "l" from your anchor result.  However, if your dataset does not actually fit with the size, you may not able to visualize it properly.

2. By the way, are you using coco dataset?

3. You may notice that the output is not normalized by image shape. This may result in some issues. I'm working on it right now to make adjustments.

**Comment by lucasjinreal** [comment]
@Cli98 Yes, default is category_id='l'.

I didn't alter the code at  all, it only prints l result by default?

So that what if I need s and m, I need recalculated again?

My dataset is VOC format and I converted to coco as well, it's self dataset.

Waiting for your commits?

**Comment by Cli98** [comment]
> @Cli98 Yes, default is category_id='l'.
> 
> I didn't alter the code at all, it only prints l result by default?
> 
> So that what if I need s and m, I need recalculated again?
> 
> My dataset is VOC format and I converted to coco as well, it's self dataset.
> 
> Waiting for your commits?

@jinfagang Yup. However, there are three categories by size in coco dataset. Namely, "Small", "medium" and "large". So for your case, I expect to see matches for large categories but few for another two. And check my examples in readme. Even a tiny change for anchor size may miss lots of bounding boxes. So If you ask me, I recommend to run for three categories separately and pick some typical anchors.

Actually you may consider that I should clearly make notes for "category" parameters. And I will make a tutorial and add this to my next update.

**Comment by Cli98** [comment]
Since there are no follow up questions, I will close this thread. Please feel free to reopen if you need.
