### ISSUE TITLE
anchor_base_scale and anchor_stride setting

### ISSUE THREAD

**Issue by BravoLu** [Cli98/anchor_computation_tool#4]
hello, thanks for your work for this repo.
I wonder how to set the params like anchor_base_scale & anchor_stride for efficientdet? 
Could you tell me the way to get above two ?

**Comment by Cli98** [comment]
Hi @BravoLu ,

Thank you for contacting me. Firstly I want to double check with you. As in efficientdet, "anchor_base_scale" and "anchor_scale" are two different concepts. So which one you are referring to?

If you are referring to anchor_scale, then please have a look for "kmean anchor size " notebook. You only need to run each cell and check result.

 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/19630616/81884038-cb66c680-9564-11ea-89c0-b2b49eee475f.png">

Last line gives what you need.

**Comment by BravoLu** [comment]
thanks for your reply.  Yes, I see the function compute_anchor_para and it recieve two params: anchor_base_scale and anchor_stride. In your annotations "Require anchor_base_scale, anchor_stride at first feature map, it depends on network configuration", I wonder how to set it in efficientdet-d0

**Comment by Cli98** [comment]
> thanks for your reply. Yes, I see the function compute_anchor_para and it recieve two params: anchor_base_scale and anchor_stride. In your annotations "Require anchor_base_scale, anchor_stride at first feature map, it depends on network configuration", I wonder how to set it in efficientdet-d0

@BravoLu Lucky you are. No need to modify any default parameter if I remember everything correctly. Yet Please allow me to double check. 
However, I need to warn you that, the result is based on absolute scale. So you if resize your input, the anchor may not suit your model. I'm actually testing my code to make it scale free. Stay tuned.

**Comment by Cli98** [comment]
Since there are no more follow up questions for now, I will close this thread. Please reopen if you need.
