### ISSUE TITLE
anchor calculation

### ISSUE THREAD

**Issue by Zheweiqiu** [Cli98/anchor_computation_tool#5]
I tried to re-calculate anchor_scale and anchor_ratio on my own dataset using method in your repo. The result accuracy is 58.11% for CLUSTER=3, what do you think about this result? Is that satisfactory？

Also, what does the parameter CLUSTER mean? I notice it controls the length of output list anchor_scale and anchor_ratio. I use EfficientDet from "Yet-Another-EfficientDet-Pytorch" and the length anchor_ratio is 3 in that repo, so I should set CLUSTER=3 in this case?
Thanks!

**Comment by Cli98** [comment]
@Zheweiqiu Hi Zheweiqiu, thank your for contacting me.

This is a good question. Anchor accuracy is measured by average of IOU and thus only represent one side of coin. From my perspective, some of the aerial image dataset can achieve similar performance with more small objects. So if you are working on dataset with small objects (such as face detection, crowd counting etc), then yes I think it is okay. However, I highly suggest to visualize them and so you can actually see how they work.

"Cluster" means how many group you want to search. Say you set it as 3, then you will find 3 anchors scale as well as 3 anchor_ratio. So finally you reach to 9 anchors (3*3) in this case. This  is case dependent and I'm not able to tell exact number unless I see visualization.

**Comment by Zheweiqiu** [comment]
@Cli98 
Thanks for your reply!
One problem I found is that I got different anchor_scale and anchor_ratio over the same dataset. The accuracy is pretty close though. And I substitute the default anchor_scale and anchor_ratio with the self-calculated results but the loss is higher. Any idea how that happened?
Here are example outputs over the same dataset.

Accuracy: 55.52%
Boxes:
 [[259 148]
 [ 55  38]
 [125  62]]
computed paras:  ([8.09375, 1.71875, 3.90625], [(1, 0.5714285714285714), (1, 0.6909090909090909), (1, 0.496)])

Accuracy: 55.52%
Boxes:
 [[125  62]
 [259 148]
 [ 55  38]]
computed paras:  ([3.90625, 8.09375, 1.71875], [(1, 0.496), (1, 0.5714285714285714), (1, 0.6909090909090909)])

Accuracy: 55.54%
Boxes:
 [[129  63]
 [ 57  39]
 [262 150]]
computed paras:  ([4.03125, 1.78125, 8.1875], [(1, 0.4883720930232558), (1, 0.6842105263157895), (1, 0.5725190839694656)])

**Comment by Cli98** [comment]
> @Cli98
> Thanks for your reply!
> One problem I found is that I got different anchor_scale and anchor_ratio over the same dataset. The accuracy is pretty close though. And I substitute the default anchor_scale and anchor_ratio with the self-calculated results but the loss is higher. Any idea how that happened?
> Here are example outputs over the same dataset.
> 
> Accuracy: 55.52%
> Boxes:
> [[259 148]
> [ 55 38]
> [125 62]]
> computed paras: ([8.09375, 1.71875, 3.90625], [(1, 0.5714285714285714), (1, 0.6909090909090909), (1, 0.496)])
> 
> Accuracy: 55.52%
> Boxes:
> [[125 62]
> [259 148]
> [ 55 38]]
> computed paras: ([3.90625, 8.09375, 1.71875], [(1, 0.496), (1, 0.5714285714285714), (1, 0.6909090909090909)])
> 
> Accuracy: 55.54%
> Boxes:
> [[129 63]
> [ 57 39]
> [262 150]]
> computed paras: ([4.03125, 1.78125, 8.1875], [(1, 0.4883720930232558), (1, 0.6842105263157895), (1, 0.5725190839694656)])

Hi @Zheweiqiu , this should be expected due to the property of kmean algorithm. However, the difference should not be too much. From your result, I think it is okay. 

"And I substitute the default anchor_scale and anchor_ratio with the self-calculated results but the loss is higher"

Which repo you are using? What is the loss you refer to? More info plz.

**Comment by Zheweiqiu** [comment]
@Cli98 
efficientdet:Yet-Another-EfficientDet-Pytorch
Both classification loss and regression loss remains at a higher level compared to default anchor setting for the same number of epoch.
For my dataset, it contains only one class and the bounding box is rectangle.

**Comment by Cli98** [comment]
> @Cli98
> efficientdet:Yet-Another-EfficientDet-Pytorch
> Both classification loss and regression loss remains at a higher level compared to default anchor setting for the same number of epoch.
> For my dataset, it contains only one class and the bounding box is rectangle.

@Zheweiqiu So you are working on detection. Let me ask,

1. Are you able to get satisfying result by using default anchors?
2. How AP changes after you modify it?

Loss tells u nothing BTW. I have argued this in that repo.
