### ISSUE TITLE
Wouldn't be better to scale the boxes?

### ISSUE THREAD

**Issue by mnslarcher** [Cli98/anchor_computation_tool#6]
Hi @Cli98, I think that in the current implementation the bbox size has too much importance.

Immagine this situation:
10 bboxes 10x5
5 bboxes 2x1
5 bboxes 1x2

If K=2 the two clusters would be:
10 bboxes 10x5

and
5 bboxes 2x1
5 bboxes 1x2

and so the suggested ratios would be (1.4, 0.7) and (1., 1.) instead of (1.4, 0.7) and (0.7, 1.4) (or (1., 0.5), (1., 2.)).

I tried this experiment with COCO annotations, I'm trying to calculate good anchors for EfficientDet0 and my dataset:
```
# load COCO train 2017 annotations
with open("instances_train2017.json") as f:
    annotations = json.load(f)
```
```
image_size = 512 #efficientdet0 input_size
min_size = 32 * 32
images_scale = {ann["id"]: image_size / max(ann["width"], ann["height"]) for ann in annotations["images"]}
scaled_bboxes = np.array([np.array(ann["bbox"][-2:]) * images_scale[ann["image_id"]] for ann in annotations["annotations"] if np.prod(ann["bbox"][-2:]) > min_size])
out = kmeans(scaled_bboxes, k=3)
# results:
2 * out / out.sum(axis=1, keepdims=True)
array([[0.91217741, 1.08782259],
       [0.914852  , 1.085148  ],
       [1.00598999, 0.99401001]])
```
As you see the ratios are very different from the suggested ones and very similar to each other.

Instead if I normalize the bboxes so they sum to 2 (like in EfficientDets libraries):
```
min_size = 32 * 32
bboxes = np.array([annotation["bbox"][-2:] for annotation in annotations["annotations"] if np.prod(annotation["bbox"][-2:]) > min_size])
nbboxes = 2 * bboxes / bboxes.sum(axis=1, keepdims=True)
out = kmeans(nbboxes , k=3)
# results:
2 * out / out.sum(axis=1, keepdims=True)
array([[0.60458624, 1.39541376],
       [0.96894304, 1.03105696],
       [1.33333333, 0.66666667]])
```
Here as you can see we obtain more or less the ratios suggested, for example, in the EfficientDet implementation

**Comment by Cli98** [comment]
> Hi @Cli98, I think that in the current implementation the bbox size has too much importance.
> 
> Immagine this situation:
> 10 bboxes 10x5
> 5 bboxes 2x1
> 5 bboxes 1x2
> 
> If K=2 the two clusters would be:
> 10 bboxes 10x5
> 
> and
> 5 bboxes 2x1
> 5 bboxes 1x2
> 
> and so the suggested ratios would be (1.4, 0.7) and (1., 1.) instead of (1.4, 0.7) and (0.7, 1.4) (or (1., 0.5), (1., 2.)).
> 
> I tried this experiment with COCO annotations, I'm trying to calculate good anchors for EfficientDet0 and my dataset:
> 
> ```
> # load COCO train 2017 annotations
> with open("instances_train2017.json") as f:
>     annotations = json.load(f)
> ```
> 
> ```
> image_size = 512 #efficientdet0 input_size
> min_size = 32 * 32
> images_scale = {ann["id"]: image_size / max(ann["width"], ann["height"]) for ann in annotations["images"]}
> scaled_bboxes = np.array([np.array(ann["bbox"][-2:]) * images_scale[ann["image_id"]] for ann in annotations["annotations"] if np.prod(ann["bbox"][-2:]) > min_size])
> out = kmeans(scaled_bboxes, k=3)
> # results:
> 2 * out / out.sum(axis=1, keepdims=True)
> array([[0.91217741, 1.08782259],
>        [0.914852  , 1.085148  ],
>        [1.00598999, 0.99401001]])
> ```
> 
> As you see the ratios are very different from the suggested ones and very similar to each other.
> 
> Instead if I normalize the bboxes so they sum to 2 (like in EfficientDets libraries):
> 
> ```
> min_size = 32 * 32
> bboxes = np.array([annotation["bbox"][-2:] for annotation in annotations["annotations"] if np.prod(annotation["bbox"][-2:]) > min_size])
> nbboxes = 2 * bboxes / bboxes.sum(axis=1, keepdims=True)
> out = kmeans(nbboxes , k=3)
> # results:
> 2 * out / out.sum(axis=1, keepdims=True)
> array([[0.60458624, 1.39541376],
>        [0.96894304, 1.03105696],
>        [1.33333333, 0.66666667]])
> ```
> 
> Here as you can see we obtain more or less the ratios suggested, for example, in the EfficientDet implementation

Hi @mnslarcher Good catch!
The reason I choose not to scale is, it is more convenient to visualize bbox on original image, which is the first tool I mention in Readme. You can definitely go with scale version and cast it back accordingly. I actually have put this into my TODO (# 3) list three days ago.

And by the way, why you use formula 2 * out / out.sum(axis=1, keepdims=True)? Any reference for the multiplier of 2? Let me know if it is possible. Thank you.

**Comment by mnslarcher** [comment]
Hi @Cli98, thanks for the answer. I use that multiplier because I'm using the EfficientDet implementation that you linked in this repo. If you see, its default anchor ratios are:

`anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'`

they sum to 2.

For this implementation is not the same to use (1.4, 0.7) or (1., 0.5) like your code would return because these values are multiplied to other values to get the anchor size (so in this example your values would produce smaller anchors:

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/f2bf780ccd84771435f6e15af3fc1d85c0f1309d/efficientdet/utils.py#L112

**Comment by Cli98** [comment]
> https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/f2bf780ccd84771435f6e15af3fc1d85c0f1309d/efficientdet/utils.py#L112

Hey @mnslarcher , thank you for sharing your thoughts. And I will do what you suggest. Just wait my update and I'm be back to you ASAP.

**Comment by mnslarcher** [comment]
Sorry @Cli98, I said something that is not correct, I didn't paid enough attention to the numbers. They don't sum to 2, they have all an area (approximately) of 1 (so the idea is to keep the area the same for all the ratios).

Instead of 
`2 * out / out.sum(axis=1, keepdims=True)`

We should do
`out / np.sqrt(out.prod(axis=1, keepdims=True))`

**Comment by Cli98** [comment]
> Sorry @Cli98, I said something that is not correct, I didn't paid enough attention to the numbers. They don't sum to 2, they have all an area (approximately) of 1 (so the idea is to keep the area the same for all the ratios).
> 
> Instead of
> `2 * out / out.sum(axis=1, keepdims=True)`
> 
> We should do
> `out / np.sqrt(out.prod(axis=1, keepdims=True))`

@mnslarcher That's exactly how faster rcnn works, correct me if I'm wrong. Additionaly, I'm also considering to normalize by image size firstly and then recast it back to adjusted scale, in case that you need to resize.

**Comment by mnslarcher** [comment]
I agree, I did the same, I also adapted the code of the original repo, see here if you like and feel free to take inspiration if you find something useful, there are some "improvments" (for example is faster):

https://github.com/mnslarcher/kmeans-anchor-ratios

**Comment by Cli98** [comment]
Issue closed due to inactivity.
