### ISSUE TITLE
Problems of CLUSTERS.

### ISSUE THREAD

**Issue by edwardning** [Cli98/anchor_computation_tool#9]
Hello!
Problems of CLUSTERS.

Is CLUSTERS=3 used in Yet-Another-EfficientDet-Pytorch?

Now I want to use your code to get the anchor of my own dataset, but I found that you added '' category_id='l' '' when calculating the anchor. It seems that the purpose is to calculate merely the anchors of large-scale target.

So, what should I do to get the right anchors. Should I set 'category_id' to a string other than 's, m, l'?

**Comment by edwardning** [comment]
I mean, what is 'category_id'？

**Comment by Cli98** [comment]
> I mean, what is 'category_id'？

category_id refers to the case where you want to specially focus on "small"/"medium"/"large" category. The definition of those three categories correspond to coco definition. 

This is useful in specialized dataset, such as aerial image dataset, where you want to generate your cluster for small category only. 

It can be disabled by setting category_id as None.

**Comment by edwardning** [comment]
> This is useful in specialized dataset, such as aerial image dataset, where you want to generate your cluster for small category only.

got it. Thankssss!
